### ISSUE TITLE
Wavelet's ledger needs to have proper shutdown mechanism

### ISSUE THREAD

**Issue by a-urth** [perlin-network/wavelet#181]
There is no proper shutdown for ledger as of now, thats why in tests we currently shut down grpc server and wait for some amount of time. Which makes tests non deterministic, since there a lot of requests still trying to access nodes and sometimes port collision happens.

**Comment by hasyimibhar** [comment]
I opened PR #147 to address this issue, but I later closed it because I felt it was not needed yet since `WithoutGC` option is introduced for `NewLedger` (GC was causing tests to panic as the GC goroutine was not killed properly between tests),

But recently I faced this issue where a node takes too long to exit. It turns out the node's HTTP server was blocking on `GracefulStop` (probably because there are processes still making requests to it). I had to switch to `Stop` [to make the tests pass](https://github.com/perlin-network/wavelet/pull/177/files#diff-b41699f57b87bee7a2a750c1b079fb63R212). While it works for now, I think it's better if we have proper shutdown for the ledger.
