### ISSUE TITLE
Extensive genesis specification support, and account/contract dumps.

### ISSUE THREAD

**Issue by iwasaki-kenta** [perlin-network/wavelet#189]
It would be useful to have a genesis/ folder available, in which the genesis of the ledgers state is compiled from all files within the folder.

An account state may be specified within the genesis/ folder in the form of a `[account address].json` file with key-value pairs.

A smart contract may be specified within the genesis/ folder in the form of a `[contract address].wasm` file with accompanying `[contract address].[page index].dmp` files representing the contracts memory pages.

Commands may also be implemented for dumping out specified account state or smart contract state like so:

dump/dmp <account/contract address> <destination folder>

**Comment by AhmadMuzakkir** [comment]
I purpose we store all the contract related files except account (pages, globals, code) into a folder with a name like [id].contract.

So the dump folder looks like this
- [Account ID].json
- [Contract ID].json
- [Contract ID].contract/
	- [Contract ID].wasm
	- [Contract ID].globals.dmp
	- [Contract ID].0.dmp
	- [Contract ID].1.dmp
	- [Contract ID].2.dmp
		....


This is to improve memory efficiency since we can read all the files from a contract, validate the files are complete and correct, and load them at one go.

Each contract must have a json account file, a wasm file, global and pages dmp files.
Otherwise, the contract dump is considered incomplete.

**Comment by iwasaki-kenta** [comment]
I believe it's not necessary to have the contract in it's own folder,  as we can simply check that for some given Account ID, if there exists [Account ID].wasm, [Account ID].globals.dmp, and [Account ID].[number].dmp, then the Account ID corresponds to a Contract ID.

**Comment by AhmadMuzakkir** [comment]
Yeah, it's not necessary. But the current way is not very memory efficient.
Since during loading, I have to walk the entire folder and keep tracks of the contract page files in a map to make sure the contract page files are complete.

I guess we can try first before improving it.

**Comment by iwasaki-kenta** [comment]
PR is ready; closing the issue for the time being. Will merge the PR in once other aspects of the codebase is cleaned up as discussed in prior internal meetings.
