### ISSUE TITLE
Peers specified as CLI args down cause stalls

### ISSUE THREAD

**Issue by rkeene** [perlin-network/wavelet#197]
If any of the peers specified as CLI arguments to "`wavelet`" are down then consensus stalls

**Comment by iwasaki-kenta** [comment]
Can't seem to reproduce it locally. I manually re-connected Node 1 to Node 2 using the `cc` command. Anymore specifics? Such as one of the nodes must be out-of-sync?

![image](https://user-images.githubusercontent.com/8392982/64074034-70dc5180-ccd8-11e9-9579-935aaec58cc3.png)

**Comment by a-urth** [comment]
@rkeene how exactly one can reproduce it?

**Comment by iwasaki-kenta** [comment]
From the looks of it, it seems that the issue isn't directly that consensus has been stalled because of a peer that is down.

Stale connections in Noise get disconnected if a message sent to said connection times out. Peer addresses that may not be dialed are ignored.

Hence, either one of the following occurs:
1) One of the peers specified as a CLI flag _is_ down, and therefore may not be connected to. K is set to 2, and so the node is not connected to enough peers. Therefore, consensus would stall.
2) The peers the node connects to, which are specified as CLI flags, are stale. The node starts syncing stale transactions which takes a longevitated amount of time, only to then notice the peers they were syncing transactions from get restarted/disconnected.

**Comment by iwasaki-kenta** [comment]
Solved by fixes in Noise.
