### ISSUE TITLE
Choose one solution for database and use it instead of abstraction.

### ISSUE THREAD

**Issue by a-urth** [perlin-network/wavelet#393]
So currently we have support for both leveldb and badgerdb and since we also have in-memory db (although leveldb provides it's own solution for that) we do not use database directly but rather through interface which is subset of common methods among all of the supported.
This leads that we cannot use unique feature of each database - like transactions and iterators for leveldb, or prefix operations for badger, or even extended operations over batches for both of them.

My proposal is to decide to use one of those (i feel like leveldb) and stick to it for a time being. We've been using leveldb for a while already and I'm not sure there is much point to switch between databases that often and not using unique feature of each of them.

Of course we can extend our interface for both storage and batch and then just through `not implemented` errors in case something is not supported in one database but is in another. But i think it will just complicate everything even more without providing marginal benefits for us.

What do you think guys?

**Comment by iwasaki-kenta** [comment]
I feel that we should opt more for BadgerDB - in the long run it is more well-maintained in comparison to the go-leveldb fork. Online backups, etc. are features that would be useful for us to provide support for too.

**Comment by a-urth** [comment]
@hasyimibhar @AhmadMuzakkir guys, do you have any comments on that topic?

**Comment by hasyimibhar** [comment]
I agree with sticking to one implementation instead of using an interface, since different implementations might have semantic differences (e.g. I ran into an issue while plugging in BadgerDB, and it turns out BadgerDB does not handle copying the inserted value, while LevelDB does). I also second Kenta that we go for BadgerDB because it has better support since it's built by a database company, while LevelDB is kind of stagnant.
